server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: HikariPool
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/master.yml
    default-schema: public
    contexts: dev

jwt:
  secret: { JWT_SECRET }
  expirationMs: 86400000
